### ISSUE TITLE
Still getting socket timeout error

### ISSUE THREAD

**Issue by pgurav** [amplience/dc-extensions-sdk#12]
![timeout-error](https://user-images.githubusercontent.com/8085793/81912492-445d3100-95ec-11ea-8c1e-cffd44f82c18.JPG)

![Capture](https://user-images.githubusercontent.com/8085793/81912662-82f2eb80-95ec-11ea-8343-710960402c3b.JPG)

Note: I am using latest SDK version 1.1.0

**Comment by pgurav** [comment]
![Capture](https://user-images.githubusercontent.com/8085793/81912662-82f2eb80-95ec-11ea-8343-710960402c3b.JPG)

**Comment by pixelscript** [comment]
The SDK doesn't use WebSockets for the connection it uses MessageChannel. What you are looking at there is the live reload functionality of the parcel bundler, a utility that would reload the app when changes are made during the local development of your app.

**Comment by pgurav** [comment]
Hi @pixelscript,

Thank you so much for the help. Yeah you are right, I have made some changes in code and now it's not showing any socket-timeout error now.

Still When I create new content in amplience by clicking on 'Create content' below error comes up
![Capture](https://user-images.githubusercontent.com/8085793/82033264-1d6d3080-96ba-11ea-8986-176da73a7152.JPG)

Above issue is there only while creating new content, it works fine when we open/modify any already existing content.

**Comment by pixelscript** [comment]
Without seeing your code it sounds like you're trying to fetch the content item before it has been created. If you wrap that part of your code in a try-catch you'll be able to handle that case.

**Comment by pixelscript** [comment]
I'm going to close this though as this isn't an issue with the SDK.
