### ISSUE TITLE
Fields Created by UI extension are missing in Json

### ISSUE THREAD

**Issue by pgurav** [amplience/dc-extensions-sdk#5]
Here is the scenario:
1.	Create new content which is using UI extension. Example: Banner
2.	Add heading text, eyebrow text and save and publish. Please don’t make any changes for any drop-down's. Let the default values be as it is.
3.	After publish check the json for the content, you can see the drop-down values are missing there
4.	Now go into the content again and make some changes in drop-down , you can just reselect whatever is default value.
5.	Again do save& publish
6.	Now check json
7.	You can see the changed/reselected dropdown value in json

**Comment by pixelscript** [comment]
Hi,

It sounds like you are having an issue with a specific extension and not the sdk in general. Going to close this issue.

Thanks
